import { createUseStyles } from "react-jss";
import { Colors } from "../../../../common/colors";
import { ThemeInterface } from "../../../../../interfaces/theme";

export const UNITS_BY_REGION = [
  {
    region: "Global",
    units: [{ code: "metric", name: "Metric (meters, kilograms, Celsius)" }],
  },
  {
    region: "North America",
    units: [
      { code: "imperial_us", name: "Imperial US (feet, pounds, Fahrenheit)" },
      { code: "metric", name: "Metric (meters, kilograms, Celsius)" },
    ],
  },
  {
    region: "Europe",
    units: [
      { code: "metric", name: "Metric (meters, kilograms, Celsius)" },
      { code: "imperial_uk", name: "Imperial UK (miles, stones, Celsius)" },
    ],
  },
  {
    region: "Asia",
    units: [{ code: "metric", name: "Metric (meters, kilograms, Celsius)" }],
  },
  {
    region: "Africa",
    units: [{ code: "metric", name: "Metric (meters, kilograms, Celsius)" }],
  },
  {
    region: "Australia",
    units: [
      { code: "metric", name: "Metric (meters, kilograms, Celsius)" },
      { code: "imperial_uk", name: "Imperial UK (miles, stones, Celsius)" },
    ],
  },
  {
    region: "South America",
    units: [{ code: "metric", name: "Metric (meters, kilograms, Celsius)" }],
  },
];

export const TIMEZONES = [
  { code: "UTC", name: "Coordinated Universal Time" },
  { code: "GMT", name: "Greenwich Mean Time" },
  { code: "PST", name: "Pacific Standard Time (UTC-8)" },
  { code: "PDT", name: "Pacific Daylight Time (UTC-7)" },
  { code: "EST", name: "Eastern Standard Time (UTC-5)" },
  { code: "EDT", name: "Eastern Daylight Time (UTC-4)" },
  { code: "CST", name: "Central Standard Time (UTC-6)" },
  { code: "CDT", name: "Central Daylight Time (UTC-5)" },
  { code: "MST", name: "Mountain Standard Time (UTC-7)" },
  { code: "MDT", name: "Mountain Daylight Time (UTC-6)" },
  { code: "IST", name: "Indian Standard Time (UTC+5:30)" },
  { code: "CET", name: "Central European Time (UTC+1)" },
  { code: "CEST", name: "Central European Summer Time (UTC+2)" },
  { code: "EET", name: "Eastern European Time (UTC+2)" },
  { code: "EEST", name: "Eastern European Summer Time (UTC+3)" },
  { code: "JST", name: "Japan Standard Time (UTC+9)" },
  { code: "AEST", name: "Australian Eastern Standard Time (UTC+10)" },
  { code: "AEDT", name: "Australian Eastern Daylight Time (UTC+11)" },
  { code: "ACST", name: "Australian Central Standard Time (UTC+9:30)" },
  { code: "ACDT", name: "Australian Central Daylight Time (UTC+10:30)" },
  { code: "NZST", name: "New Zealand Standard Time (UTC+12)" },
  { code: "NZDT", name: "New Zealand Daylight Time (UTC+13)" },
  { code: "WET", name: "Western European Time (UTC+0)" },
  { code: "WEST", name: "Western European Summer Time (UTC+1)" },
  { code: "ART", name: "Argentina Time (UTC-3)" },
  { code: "AST", name: "Atlantic Standard Time (UTC-4)" },
  { code: "ADT", name: "Atlantic Daylight Time (UTC-3)" },
  { code: "HST", name: "Hawaii-Aleutian Standard Time (UTC-10)" },
  { code: "AKST", name: "Alaska Standard Time (UTC-9)" },
  { code: "AKDT", name: "Alaska Daylight Time (UTC-8)" },
  { code: "SGT", name: "Singapore Time (UTC+8)" },
  { code: "CAT", name: "Central Africa Time (UTC+2)" },
  { code: "WAT", name: "West Africa Time (UTC+1)" },
  { code: "EAT", name: "East Africa Time (UTC+3)" },
  { code: "MSK", name: "Moscow Standard Time (UTC+3)" },
];

export const CURRENCIES = [
  { code: "USD", name: "US Dollar" },
  { code: "EUR", name: "Euro" },
  { code: "PKR", name: "Pakistani Rupee" },
  { code: "GBP", name: "British Pound" },
  { code: "JPY", name: "Japanese Yen" },
  { code: "CAD", name: "Canadian Dollar" },
  { code: "AUD", name: "Australian Dollar" },
  { code: "CHF", name: "Swiss Franc" },
  { code: "CNY", name: "Chinese Yuan" },
  { code: "INR", name: "Indian Rupee" },
  { code: "BRL", name: "Brazilian Real" },
  { code: "RUB", name: "Russian Ruble" },
  { code: "MXN", name: "Mexican Peso" },
  { code: "ZAR", name: "South African Rand" },
  { code: "SGD", name: "Singapore Dollar" },
  { code: "HKD", name: "Hong Kong Dollar" },
  { code: "KRW", name: "South Korean Won" },
  { code: "SEK", name: "Swedish Krona" },
  { code: "NOK", name: "Norwegian Krone" },
  { code: "DKK", name: "Danish Krone" },
  { code: "MYR", name: "Malaysian Ringgit" },
  { code: "THB", name: "Thai Baht" },
  { code: "IDR", name: "Indonesian Rupiah" },
  { code: "TRY", name: "Turkish Lira" },
  { code: "AED", name: "UAE Dirham" },
  { code: "SAR", name: "Saudi Riyal" },
  { code: "ILS", name: "Israeli New Shekel" },
  { code: "PLN", name: "Polish Zloty" },
  { code: "NZD", name: "New Zealand Dollar" },
  { code: "EGP", name: "Egyptian Pound" },
  { code: "PHP", name: "Philippine Peso" },
  { code: "CZK", name: "Czech Koruna" },
  { code: "HUF", name: "Hungarian Forint" },
  { code: "RON", name: "Romanian Leu" },
  { code: "BGN", name: "Bulgarian Lev" },
  { code: "HRK", name: "Croatian Kuna" },
  { code: "LKR", name: "Sri Lankan Rupee" },
  { code: "NPR", name: "Nepalese Rupee" },
  { code: "VND", name: "Vietnamese Dong" },
  { code: "BDT", name: "Bangladeshi Taka" },
  { code: "TWD", name: "New Taiwan Dollar" },
  { code: "MXV", name: "Mexican Unidad de Inversión" },
  { code: "XOF", name: "West African CFA Franc" },
  { code: "XAF", name: "Central African CFA Franc" },
  { code: "XPF", name: "CFP Franc" },
  { code: "AWG", name: "Aruban Florin" },
  { code: "DOP", name: "Dominican Peso" },
  { code: "KZT", name: "Kazakhstani Tenge" },
  { code: "GHS", name: "Ghanaian Cedi" },
  { code: "BMD", name: "Bermudian Dollar" },
  { code: "SYP", name: "Syrian Pound" },
  { code: "QAR", name: "Qatari Rial" },
  { code: "JOD", name: "Jordanian Dinar" },
  { code: "TND", name: "Tunisian Dinar" },
  { code: "MOP", name: "Macanese Pataca" },
  { code: "NAD", name: "Namibian Dollar" },
  { code: "ZMW", name: "Zambian Kwacha" },
  { code: "BZD", name: "Belize Dollar" },
  { code: "PEN", name: "Peruvian Nuevo Sol" },
  { code: "CLP", name: "Chilean Peso" },
  { code: "COP", name: "Colombian Peso" },
  { code: "GEL", name: "Georgian Lari" },
  { code: "KWD", name: "Kuwaiti Dinar" },
  { code: "OMR", name: "Omani Rial" },
  { code: "AFN", name: "Afghan Afghani" },
  { code: "AZN", name: "Azerbaijani Manat" },
  { code: "MDL", name: "Moldovan Leu" },
  { code: "MVR", name: "Maldivian Rufiyaa" },
  { code: "XCD", name: "East Caribbean Dollar" },
  { code: "FJD", name: "Fijian Dollar" },
  { code: "SRD", name: "Surinamese Dollar" },
  { code: "WST", name: "Samoan Tala" },
  { code: "TJS", name: "Tajikistani Somoni" },
  { code: "BAM", name: "Bosnia-Herzegovina Convertible Mark" },
  { code: "MKD", name: "Macedonian Denar" },
  { code: "LYD", name: "Libyan Dinar" },
  { code: "KGS", name: "Kyrgyzstani Som" },
  { code: "GMD", name: "Gambian Dalasi" },
  { code: "LSL", name: "Lesotho Loti" },
  { code: "SLL", name: "Sierra Leonean Leone" },
  { code: "XAF", name: "Central African CFA Franc" },
  { code: "ETB", name: "Ethiopian Birr" },
  { code: "RWF", name: "Rwandan Franc" },
  { code: "AWG", name: "Aruban Florin" },
  { code: "DZD", name: "Algerian Dinar" },
  { code: "KMF", name: "Comorian Franc" },
  { code: "STN", name: "Sao Tome and Principe Dobra" },
];

export const useStylesFromThemeFunction = createUseStyles(
  (theme: ThemeInterface) => {
    return {
      container: {
        width: "100%",
        height: "1100px",
        minWidth: "fit-content",
        alignItems: "center",
        justifyContent: "space-between",
        padding: "10px",
        margin: "2px",
        borderRadius: "10px",
        backgroundColor: Colors.blueGrayLight,
      },
      formWrapper: {
        display: "flex",
        flexDirection: "column",
        width: "100%",
        gap: "10px",
        alignItems: "center",
        justifyContent: "center",
        paddingLeft: "25%",
        paddingRight: "25%",
      },
    };
  }
);
